blocklist_packages:
  - python3-requests

update_interval: 86400 # 1 days in seconds

blocklists:
  - id: adaway
    name: AdAway
    enabled: true
    assets:
      - id: adaway_hosts
        feed: adaway_feed
        dataset: adaway_hosts_dataset
        parser: adaway_parser
        preserve_artifacts: false

  - id: urlhaus
    name: URLHaus
    enabled: true
    assets:
      - id: urlhaus
        feed: urlhaus_feed
        dataset: urlhaus_rpz_dataset
        parser: urlhaus_parser
        preserve_artifacts: false

  - id: threatfox
    name: ThreatFox
    enabled: true
    assets:
      - id: threatfox
        feed: threatfox_feed
        dataset: threatfox_json_dataset
        parser: threatfox_parser
        preserve_artifacts: true
