blocklist_packages:
  - python3-requests

update_interval: 86400 # 1 days in seconds

blocklists:
  - id: adaway
    name: AdAway
    enabled: true
    assets:
      - id: adaway_hosts
        feed_name: adaway_feed
        dataset_name: adaway_hosts_dataset
        parser_name: adaway_parser
        preserve_artifacts: true

  - id: urlhaus
    name: URLHaus
    enabled: true
    assets:
      - id: urlhaus
        feed_name: urlhaus_feed
        dataset_name: urlhaus_rpz_dataset
        parser_name: urlhaus_parser
        preserve_artifacts: true

  - id: threatfox
    name: ThreatFox
    enabled: true
    assets:
      - id: threatfox
        feed_name: threatfox_feed
        dataset_name: threatfox_json_dataset
        parser_name: threatfox_parser
        preserve_artifacts: true
