interface wlan0
{
    AdvSendAdvert on;
    MaxRtrAdvInterval 60;
    MinRtrAdvInterval 20;

    prefix 2601:8c0:b02:2120::/64
    {
        AdvOnLink on;
        AdvAutonomous on;
        AdvRouterAddr on;

        RDNSS 2606:4700:4700::1111 2620:fe::fe
        {
            AdvRDNSS on;
        };
    };
};