# =========================================================
# 1. BASE PACKAGES
# =========================================================
- name: Ensure ui base packages are installed
  apt:
    name: "{{ ui_packages }}"
    state: present
    update_cache: yes

# =========================================================
# 2. DEPLOY UI PYTHON COMPONENTS
# =========================================================
- name: Ensure clean slate for JANR UI
  file:
    path: /opt/janr/ui
    state: absent
  failed_when: false

- name: Create/Recreate JANR UI directory
  file:
    path: /opt/janr/ui
    state: directory
    owner: root
    group: janr-admin
    mode: "0770"

- name: Set permissions for /opt/janr
  file: 
    path: /opt/janr
    owner: root
    group: janr-admin
    mode: "0770"
    recurse: true

- name: Copy UI src into /opt/janr/ui
  copy:
    src: src/
    dest: /opt/janr/ui/
    owner: root
    group: janr-admin
    mode: "0770"

- name: Ensure dashboard is executable
  file:
    path: /opt/janr/ui/dashboard.py
    owner: root
    group: janr-admin
    mode: "0770"

# =========================================================
# 3. CREATE LAUNCHER
# =========================================================
- name: Install janr-dashboard system-wide command
  become: true
  copy:
    dest: /usr/local/bin/janr-dashboard
    mode: "0750"
    owner: root
    group: janr-admin
    content: |
      #!/usr/bin/env bash
      exec /opt/janr/ui/dashboard.py "$@"

# =========================================================
# 4. CREATE RESEVED IP FILES
# =========================================================
- name: Create dnsmasq reserved IP file
  template:
    src: janr-dnsmasq-reserved-ips.conf.j2
    dest: /etc/dnsmasq.d/janr-dnsmasq-reserved-ips.conf
    owner: root
    group: janr-admin
    mode: "0660"
    force: no

- name: Create unbound reserved IP file
  template:
    src: janr-unbound-reserved-ips.conf.j2
    dest: /etc/unbound/unbound.conf.d/janr-unbound-reserved-ips.conf
    owner: root
    group: janr-admin
    mode: "0660"
    force: no 