# === Sample Ansible Inventory File ===============================
# Sample Ansible inventory file for JanR's Orange Pi Armbian setup
# This file should be copied to hosts.ini and edited with the 
# correct values for your environment.    
# =================================================================
[router]
janr ansible_host=127.0.0.1 ansible_user=ansible_user ansible_password=ansible_password

[router:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become_password=ansible_become_password
