# === Sample Ansible Variable File ===============================
# Sample Ansible variable file for JanR's Orange Pi Armbian setup
# This file should be copied to all.yml and edited with the 
# correct values for your environment.    
# =================================================================

country_code: US
wan_interface: enx00e04c681aa4

link_watchdog_logfile: /var/log/link-watchdog.log
link_watchdog_interval: 60

upstream_dns_servers:
  - 1.1.1.1
  - 8.8.8.8

dhcp_lease_time: 12h

five_g_lan_ip: 10.10.0.1/24
five_g_dhcp_start: 10.10.0.100
five_g_dhcp_end: 10.10.0.150
five_g_ssid: JANR-5G
five_g_wifi_password: 1joshua1
five_g_wifi_channel: 149
five_g_lan_interface: wlan0

two_g_lan_ip: 10.10.1.1/24
two_g_dhcp_start: 10.10.1.100
two_g_dhcp_end: 10.10.1.150
two_g_ssid: JANR-2G
two_g_wifi_password: 1joshua1
two_g_wifi_channel: 11
two_g_lan_interface: wlx0022f4d9292b