- name: Configure JANR API credentials
  hosts: janr
  become: true

  vars_prompt:
    - name: janr_threatfox_api_key
      prompt: "Enter API key for ThreatFox"
      private: true
      confirm: true

  roles:
    - role: credentials