# -------------------------------------------------
# BASE PACKAGES
# -------------------------------------------------
- name: Ensure blocklist base packages are installed
  apt:
    name: "{{ blocklist_packages }}"
    state: present
    update_cache: yes

# -------------------------------------------------
# Ensure Runtime Directories Exist
# -------------------------------------------------
- name: Ensure JANR blocklist runtime directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: janr-admin
  loop:
    - /run/janr/blocklist/downloads
    - /run/janr/blocklist/rpz

# -------------------------------------------------
# SETUP LOGGING
# -------------------------------------------------

- name: Configure JANR blocklist log rotation
  copy:
    dest: /etc/logrotate.d/janr-blocklist
    content: |
      /run/janr/log/blocklist.log {
          size 10M
          rotate 3
          missingok
          notifempty
          copytruncate
      }

- name: Symlink blocklist log
  file:
    src: /run/janr/log/blocklist.log
    dest: /var/log/janr/blocklist.log
    state: link
    force: true

# -------------------------------------------------
# Deploy JANR Blocklist
# -------------------------------------------------
- name: Remove Previous deployment of JANR Blocklist
  file:
    path: /opt/janr/blocklist
    state: absent

- name: Create JANR blocklist directory
  file:
    path: /opt/janr/blocklist
    state: directory
    owner: root
    group: janr-admin
    mode: "0755"

- name: Deploy src to /opt/janr/blocklist
  copy:
    src: src/
    dest: /opt/janr/blocklist/
    owner: root
    group: janr-admin
    mode: "0755"

- name: Create JANR blocklist config (generated python file)
  template:
    src: janr_blocklists.py.j2
    dest: /opt/janr/blocklist/janr_blocklists.py
    mode: "0665"
    owner: root
    group: janr-admin

# -------------------------------------------------
# SYSTEMD
# -------------------------------------------------

- name: Deploy systemd service for blocklist deployment
  template:
    src: janr-blocklists.service.j2
    dest: /etc/systemd/system/janr-blocklists.service
    mode: "0644"

- name: Deploy systemd timer for blocklist updates
  template:
    src: janr-blocklists.timer.j2
    dest: /etc/systemd/system/janr-blocklists.timer
    mode: "0644"

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Enable and start JANR blocklist timer
  systemd:
    name: janr-blocklists.timer
    enabled: true
    state: started

- name: Run initial blocklist deployment immediately
  systemd:
    name: janr-blocklists.service
    state: started
